apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    env: dev-database
spec:
  containers:
    - name: postgres
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: mysecretpassword