apiVersion: v1
kind: Service
metadata:
  name: image-processing
  labels:
    app: myapp
spec:
  type: ClusterIp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    tier: backend